const routes = require('express').Router()
const productController = require('../controller/ProductController')
routes.post('/add',productController.addProduct)
routes.get('/product/:id',productController.getProductById)
routes.get('/products',productController.getAllProduct)
routes.delete('/delete/:id',productController.deleteProduct)
routes.post('/addwithfile', productController.addProductWithFile)
routes.put('/updateproduct/:id' , productController.updateProduct)
routes.get('/getallproductsbyuserid/:userId' , productController.getAllProductsByUserId)
routes.get('/totalproduct' , productController.getTotalProductCount)
module.exports = routes              